### ISSUE TITLE
Heroku bot error

### ISSUE THREAD

**Issue by gosndka** [Spark-X-Cloud/SparkXcloud-Gdrive-MirrorBot#4]
Traceback (most recent call last):

2021-12-28T14:29:58.499252+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main

2021-12-28T14:29:58.499537+00:00 app[web.1]:     return _run_code(code, main_globals, None,

2021-12-28T14:29:58.499554+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code

2021-12-28T14:29:58.499769+00:00 app[web.1]:     exec(code, run_globals)

2021-12-28T14:29:58.499784+00:00 app[web.1]:   File "/usr/src/app/bot/main.py", line 20, in <module>

2021-12-28T14:29:58.499965+00:00 app[web.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, torrent_search, delete, speedtest, count, config, updates, usage

2021-12-28T14:29:58.499991+00:00 app[web.1]:   File "/usr/src/app/bot/modules/watch.py", line 29

2021-12-28T14:29:58.500015+00:00 app[web.1]:     if link.startswith("|") or link.startswith("pswd: "):

2021-12-28T14:29:58.500043+00:00 app[web.1]:     ^

2021-12-28T14:29:58.500076+00:00 app[web.1]: IndentationError: unexpected indent

**Comment by harshhaareddy** [comment]
_**Fixed Problem**_ !!!
